### ISSUE TITLE
CoinGecko API always throws a 403 (Forbidden) response.

### ISSUE THREAD

**Issue by VolodymyrPanasyuk** [davidivkovic/coinmarketcap#2]
I am creating a project similar to yours and few days ago CoinGecko API starts allways throws a 403 (Forbidden) response.
Here is a little fix for it:
Add to CoinGeckoClient constructor this code
```c#
 _httpClient.DefaultRequestHeaders.UserAgent.ParseAdd("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36");
```

**Comment by davidivkovic** [comment]
Hey Volodymyr, thank you for the fix!
I will be adding it soon with some other fixes and improvements.

**Comment by davidivkovic** [comment]
I've just looked at the new API docs for CoinGecko and it seems that they massively reduced their requests/min limit.
It is only 10-30 now. The original free API had a 50 requests/second limit.

Do you know of any good alternatives? @VolodymyrPanasyuk

**Comment by VolodymyrPanasyuk** [comment]
@davidivkovic I use CoinGecko and CoinCap API's in my [CryptoInfoApp](https://github.com/VolodymyrPanasyuk/CryptoInfoApp) project.
I also implement the functionality: if first API throws any exception, then app notify user and trying to get data from other API. I also implemented caching of pages and charts to less often get response: 429 (To many requests).
So i can recommend you add caching to your app and to use this API's:
- [CoinCap API;](https://docs.coincap.io/)
- [CoinMarketCap API.](https://coinmarketcap.com/api/)
